services:
  db:
    image: postgres:16-alpine
    container_name: munsel_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: munsel
      POSTGRES_PASSWORD: munsel_secret
      POSTGRES_DB: munsel_mn
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
